version: '3.8'

services:
  deployment-agent:
    build:
      context: ./deployment-agent
      dockerfile: Dockerfile
    ports:
      - "2547:2547"
    networks:
      - rust-network

  balancer:
    build:
      context: ./balancer
      dockerfile: Dockerfile
    ports:
      - "2548:2548"
    networks:
      - rust-network
    depends_on:
      - deployment-agent

networks:
  rust-network:
    driver: bridge
