version: '3.8'

services:
  deployment-agent:
    build:
      context: ./deployment-agent
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT_DEPLOYMENT_AGENT}:2547"
    networks:
      - rust-network
    volumes:
      - "${DOCKER_SOCKET_VOLUME}:${DOCKER_SOCKET_VOLUME}"
    environment:
      - DOCKER_HOST=${DOCKER_HOST}

  balancer:
    build:
      context: ./balancer
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT_BALANCER}:2548"
    networks:
      - rust-network
    depends_on:
      - deployment-agent

#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    environment:
#      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
#    ports:
#      - "${PORT_GRAFANA}:3000"
#    volumes:
#      - grafana-data:/var/lib/grafana
#      - ./provisioning:/etc/grafana/provisioning

#volumes:
#  grafana-data:

networks:
  rust-network:
    driver: bridge
