version: '3.8'

services:
  server:
    build:
      context: ./deployment-agent
      dockerfile: Dockerfile
    ports:
      - "2547:2547"
    networks:
      - rust-network

  client:
    build:
      context: ./balancer
      dockerfile: Dockerfile
    networks:
      - rust-network
    depends_on:
      - server

networks:
  rust-network:
    driver: bridge
