services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - rust-network
    environment:
      - REDIS_PORT=${REDIS_PORT}

  deployment-agent:
    build:
      context: ./deployment-agent
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT_WS_DEPLOYMENT_AGENT}:${HOST_PORT_WS_DEPLOYMENT_AGENT}"
      - "${HOST_PORT_HTTP_DEPLOYMENT_AGENT}:${HOST_PORT_HTTP_DEPLOYMENT_AGENT}"
    networks:
      - rust-network
    volumes:
      - "${DOCKER_SOCKET_VOLUME}:${DOCKER_SOCKET_VOLUME}"
    environment:
      - DOCKER_HOST=${DOCKER_HOST}
      - DOCKER_IMAGE=${DOCKER_IMAGE}
      - TARGET_PORT=${TARGET_PORT}
      - DEFAULT_CONTAINER=${DEFAULT_CONTAINER}
      - APP_IDENTIFIER=${APP_IDENTIFIER}
      - HOST_PORT_WS_DEPLOYMENT_AGENT=${HOST_PORT_WS_DEPLOYMENT_AGENT}
      - HOST_PORT_HTTP_DEPLOYMENT_AGENT=${HOST_PORT_HTTP_DEPLOYMENT_AGENT}
      - HOST_IP_HOST_INTERNAL=host.docker.internal
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - HOST_IP_HOST_INTERNAL=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "${PORT_DASHBOARD}:${PORT_DASHBOARD}"
    environment:
      - DEPLOYMENT_URL=http://deployment-agent:${HOST_PORT_HTTP_DEPLOYMENT_AGENT}/stats
      - PORT_DASHBOARD=${PORT_DASHBOARD}
      - HOST_IP_HOST_INTERNAL=host.docker.internal
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - deployment-agent
      - redis
    networks:
      - rust-network
    restart: unless-stopped

  balancer:
    build:
      context: ./balancer
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT_HTTP_BALANCER}:${HOST_PORT_HTTP_BALANCER}"
    networks:
      - rust-network
    depends_on:
      - deployment-agent
      - redis
    environment:
      - HOST_PORT_WS_BALANCER=${HOST_PORT_WS_BALANCER}
      - HOST_PORT_HTTP_BALANCER=${HOST_PORT_HTTP_BALANCER}
      - HOST_PORT_WS_DEPLOYMENT_AGENT=${HOST_PORT_WS_DEPLOYMENT_AGENT}
      - HOST_IP_HOST_INTERNAL=host.docker.internal
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TARGET_PORT=${TARGET_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  rust-network:
    driver: bridge
