version: '3.8'

services:
  deployment-agent:
    build:
      context: ./deployment-agent
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT_WS_DEPLOYMENT_AGENT}:${HOST_PORT_WS_DEPLOYMENT_AGENT}"
      - "${HOST_PORT_HTTP_DEPLOYMENT_AGENT}:${HOST_PORT_HTTP_DEPLOYMENT_AGENT}"
    networks:
      - rust-network
    volumes:
      - "${DOCKER_SOCKET_VOLUME}:${DOCKER_SOCKET_VOLUME}"
    environment:
      - DOCKER_HOST=${DOCKER_HOST}
      - DOCKER_IMAGE=${DOCKER_IMAGE}
      - TARGET_PORT=${TARGET_PORT}
      - DEFAULT_CONTAINER=${DEFAULT_CONTAINER}
      - APP_IDENTIFIER=${APP_IDENTIFIER}
      - HOST_PORT_HTTP_DEPLOYMENT_AGENT=${HOST_PORT_HTTP_DEPLOYMENT_AGENT}

#  balancer:
#    build:
#      context: ./balancer
#      dockerfile: Dockerfile
#    ports:
#     - "${HOST_PORT_BALANCER}:2548"
#    networks:
#      - rust-network
#    depends_on:
#      - deployment-agent

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "${PORT_DASHBOARD}:${PORT_DASHBOARD}"
    environment:
      - DEPLOYMENT_URL=http://deployment-agent:${HOST_PORT_HTTP_DEPLOYMENT_AGENT}/stats
      - PORT_DASHBOARD=${PORT_DASHBOARD}
    depends_on:
      - deployment-agent
    networks:
      - rust-network

networks:
  rust-network:
    driver: bridge
