version: '3.8'

services:
  deployment-agent:
    build:
      context: ./deployment-agent
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT_DEPLOYMENT_AGENT}:2547"
    networks:
      - rust-network
    volumes:
      - "${DOCKER_SOCKET_VOLUME}:${DOCKER_SOCKET_VOLUME}"
    environment:
      - DOCKER_HOST=${DOCKER_HOST}

  balancer:
    build:
      context: ./balancer
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT_BALANCER}:2548"
    networks:
      - rust-network
    depends_on:
      - deployment-agent

networks:
  rust-network:
    driver: bridge
