#!/bin/bash

ENV_FILE_PATH="../.env"

# Default values
DEFAULT_DOCKER_HOST="unix:///var/run/docker.sock"
DEFAULT_DOCKER_SOCKET_VOLUME="/var/run/docker.sock"
DEFAULT_DOCKER_IMAGE="mxmller/rustybalancer-playground:latest"
DEFAULT_HOST_PORT_WS_DEPLOYMENT_AGENT="2547"
DEFAULT_HOST_PORT_WS_BALANCER="2551"
DEFAULT_HOST_PORT_HTTP_DEPLOYMENT_AGENT="2550"
DEFAULT_HOST_PORT_HTTP_BALANCER="2548"
DEFAULT_PORT_DASHBOARD="8501"
DEFAULT_TARGET_PORT="5000"
DEFAULT_DEFAULT_CONTAINER="5"
DEFAULT_APP_IDENTIFIER="RUSTYBALANCER"
DEFAULT_REDIS_PORT="6379"
DEFAULT_REDIS_HOST="redis"
DEFAULT_REDIS_INSIGHT_PORT="5540"
DEFAULT_HIGH_LOAD_THRESHOLD="55.0"
DEFAULT_LOW_LOAD_THRESHOLD="20.0"
DEFAULT_CRITICAL_LOAD_THRESHOLD="80.0"
DEFAULT_MAX_CONTAINERS="15"
DEFAULT_COOLDOWN_PERIOD="5"
DEFAULT_SCALE_STEP="1"
DEFAULT_SCALE_CHECK_PERIOD="10"
DEFAULT_CPU_WEIGHT="0.35"
DEFAULT_MEMORY_WEIGHT="0.25"
DEFAULT_NETWORK_WEIGHT="0.15"
DEFAULT_AVAILABILITY_WEIGHT="0.25"
DEFAULT_HISTORY_SIZE="20"
DEFAULT_BEST_TIME_WINDOW="10"
DEFAULT_EMA_ALPHA="0.2"
DEFAULT_REQUEST_TIMEOUT="30"
DEFAULT_CACHE_CAPACITY="10000"

# Function to create .env-file
create_env_file() {
  cat <<EOF > "$ENV_FILE_PATH"
# Docker Configuration
DOCKER_HOST=$1
DOCKER_SOCKET_VOLUME=$2
DOCKER_IMAGE=$3

# Port Configuration
# WebSocket Ports
HOST_PORT_WS_DEPLOYMENT_AGENT=$4
HOST_PORT_WS_BALANCER=$5

# HTTP Ports
HOST_PORT_HTTP_DEPLOYMENT_AGENT=$6
HOST_PORT_HTTP_BALANCER=$7

# Dashboard Port
PORT_DASHBOARD=$8

# Target Port
TARGET_PORT=$9

# Application Configuration
DEFAULT_CONTAINER=${10}
APP_IDENTIFIER=${11}

# Redis Configuration
REDIS_PORT=${12}
REDIS_HOST=${13}
REDIS_INSIGHT_PORT=${14}

# Load thresholds
HIGH_LOAD_THRESHOLD=${15}
LOW_LOAD_THRESHOLD=${16}
CRITICAL_LOAD_THRESHOLD=${17}

# Scaling Configuration
MAX_CONTAINERS=${18}
COOLDOWN_PERIOD=${19}
SCALE_STEP=${20}
SCALE_CHECK_PERIOD=${21}

# Score Weights
CPU_WEIGHT=${22}
MEMORY_WEIGHT=${23}
NETWORK_WEIGHT=${24}
AVAILABILITY_WEIGHT=${25}

# Other Settings
HISTORY_SIZE=${26}
BEST_TIME_WINDOW=${27}
EMA_ALPHA=${28} # Exponential Moving Average smoothing factor
REQUEST_TIMEOUT=${29}
CACHE_CAPACITY=${30}
EOF
}

# Choosing either expert or basic version for setup
echo "This script will generate your .env-file."
echo "Which version do you want to use:"
echo "1) Basic version (default values)"
echo "2) Expert version (you can choose your own values)"

read -p "Your choice: " choice

if [ "$choice" == "1" ]; then
    echo "Creating .env-file with default values..."
    create_env_file "$DEFAULT_DOCKER_HOST"  "$DEFAULT_DOCKER_SOCKET_VOLUME" "$DEFAULT_DOCKER_IMAGE"  "$DEFAULT_HOST_PORT_WS_DEPLOYMENT_AGENT" "$DEFAULT_HOST_PORT_WS_BALANCER" "$DEFAULT_HOST_PORT_HTTP_DEPLOYMENT_AGENT" "$DEFAULT_HOST_PORT_HTTP_BALANCER" "$DEFAULT_PORT_DASHBOARD" "$DEFAULT_TARGET_PORT" "$DEFAULT_DEFAULT_CONTAINER" "$DEFAULT_APP_IDENTIFIER" "$DEFAULT_REDIS_PORT" "$DEFAULT_REDIS_HOST" "$DEFAULT_REDIS_INSIGHT_PORT" "$DEFAULT_HIGH_LOAD_THRESHOLD" "$DEFAULT_LOW_LOAD_THRESHOLD" "$DEFAULT_CRITICAL_LOAD_THRESHOLD" "$DEFAULT_MAX_CONTAINERS" "$DEFAULT_COOLDOWN_PERIOD" "$DEFAULT_SCALE_STEP" "$DEFAULT_SCALE_CHECK_PERIOD" "$DEFAULT_CPU_WEIGHT" "$DEFAULT_MEMORY_WEIGHT" "$DEFAULT_NETWORK_WEIGHT" "$DEFAULT_AVAILABILITY_WEIGHT" "$DEFAULT_HISTORY_SIZE" "$DEFAULT_BEST_TIME_WINDOW" "$DEFAULT_EMA_ALPHA" "$DEFAULT_REQUEST_TIMEOUT" "$DEFAULT_CACHE_CAPACITY"
    echo ".env-file created."

elif [ "$choice" == "2" ]; then
    echo "Creating .env-file - expert version"
    create_env_file ! "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
    echo ".env-file created."
else
    echo "Invalid input. Please enter your choice between 1 and 2 again."
    exit 1
fi
