site_name: RustyBalancer Docs
theme:
  name: terminal
  palette: pink
  features:
    - footer.prev_next

nav:
  - Home: 'index.md'
  - Getting Started:
    - Index: 'getting-started.md'
    - Setup: 'getting-started/setup.md'
    - Environment: 'getting-started/env.md'
  - Components:
      - Index: 'components.md'
      - Balancer: 'components/balancer.md'
      - Deployment Agent: 'components/deployment-agent.md'
