
site_url: https://mxmueller.github.io/rustybalancer/
repo_url: https://github.com/mxmueller/rustybalancer
copyright: Copyright 2024 Berger, Mueller. All rights reserved
site_author: ntno

site_name: RustyBalancer Docs
theme:
  name: terminal
  palette: pink
  features:
    - footer.prev_next
    - navigation.side.indexes
    - revision.date
    - revision.history

plugins:
  - search
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "18.172vw"

nav:
  - Home: 'index.md'
  - Setup: 'setup.md'
  - Environment: 'env.md'
  - Components:
      - Index: 'components.md'
      - Balancer: 'components/balancer.md'
      - Deployment Agent: 'components/deployment-agent.md'
      - Redis: 'components/redis.md'
      - Dashboard: 'components/dashboard.md'
  - Demo:
    - Index: 'tutorial.md'
    - Setup Process: './tutorial/setup.md'
    - Starting the System: './tutorial/startup.md'
    - Key Components: './tutorial/components.md'
    - High Traffic Behavior: './tutorial/traffic.md'
    - Load Testing: './tutorial/load.md'